version: "3.11"
services:
  redis:
    image: redis:alpine
  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

