[REDIS]
host = "redis"
port = 6379
db = 0

[IMAGE_TYPES]
image_types = ["image/jpeg", "image/apng", "image/avif", "image/gif", "image/png", "image/svg", "image/xml", "image/webp"]

[REGEX_PATTERNS]
domain = "\\b(?:https?://)?(?:www\\.)?([A-Za-z0-9.-]+)\\b"
url = "(?i)\\b((?:https?://|www\\d{0,3}[.]|[a-z0-9.\\-]+[.][a-z]{2,4}/)(?:[^\\s()<>]+|(\\([^\\s()<>]+|(\\([^\\s()<>]+\\))*\\))*(\\([^\\s()<>]+|(\\([^\\s()<>]+\\))*\\))|[^\\s`!()\\[\\]{};:'\".,<>?«»“”‘’]))"
date = "\\b(?:\\d{1,2}[./-]){2}\\d{2,4}\\b"
credit_card_1 = "\\b(?:\\d{4}-){3}\\d{4}\\b"
credit_card_2 = "\\b(?:\\d{4}\\s){3}\\d{4}\\b"
credit_card_3 = "\\b\\d{16}\\b"
email = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
hash = "\\b[A-Fa-f0-9]{32}\\b|\\b[A-Fa-f0-9]{40}\\b|\\b[A-Fa-f0-9]{64}\\b"
id_number = "\\b\\d{11}\\b"
phone_number = "\\b(\\+90|0)?\\s*(\\(\\d{3}\\)[\\s-]*\\d{3}[\\s-]*\\d{2}[\\s-]*\\d{2}|\\(\\d{3}\\)[\\s-]*\\d{3}[\\s-]*\\d{4}|\\(\\d{3}\\)[\\s-]*\\d{7}|\\d{3}[\\s-]*\\d{3}[\\s-]*\\d{4}|\\d{3}[\\s-]*\\d{3}[\\s-]*\\d{2}[\\s-]*\\d{2}|\\d{12})\\b"
plate = "\\b\\d{2}\\s?[A-Z]{1,3}\\s?\\d{2,4}\\b"
combo_list = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b:[A-Za-z0-9]+|\\b[A-Za-z0-9]+:[A-Za-z0-9]+\\b"
